# Generated by Django 5.1.1 on 2024-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_incident_alter_sosrequest_emergency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
