# Generated by Django 5.1.1 on 2024-11-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_sosrequest_latitude_alter_sosrequest_longitude'),
        ('app1', '0003_sosrequest_is_active'),
    ]

    operations = [
    ]
